language: node_js
node_js:
  - "node"
script:
  - yarn run examples:lint
  - yarn run examples:test
branches:
  only:
    - master
cache:
  yarn: true
  directories:
  - examples/async/node_modules
  - examples/counter/node_modules
  - examples/real-world/node_modules
  - examples/shopping-cart/node_modules
  - examples/todomvc/node_modules
  - examples/todos/node_modules
  - examples/todos-with-undo/node_modules
  - examples/tree-view/node_modules
  - examples/universal/node_modules
